name: planet_verse
description: Space Themed Strategy Game in Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  after_layout: ^1.1.0
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  flutter_animated_dialog: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  lottie: ^2.7.0
  sizer: ^2.0.13
  rive: ^0.12.4
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.4
  fluttertoast: ^8.0.7
  in_app_review: ^2.0.2
  font_awesome_flutter: ^10.6.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0  

flutter:

  uses-material-design: true

  assets:
      - assets/animations/
      - assets/img/
      - assets/img/planets/
      - assets/img/buildings/
      - assets/img/ships/attack/
      - assets/img/ships/defense/
      - assets/img/control_deck/
      - assets/img/ruler/
      - assets/img/gifs/

  fonts:
    - family: Italianno
      fonts:
        - asset: assets/fonts/Italianno-Regular.ttf
          style: italic
    - family: Astral
      fonts:
        - asset: assets/fonts/Astral-Delight.ttf  

